### ISSUE TITLE
Convention for rim data?

### ISSUE THREAD

**Issue by mtanneau** [JuliaSmoothOptimizers/QPSReader.jl#14]
MPS files may have multiple objective rows, right-hand sides, etc... which is currently not handled in the code.
* The objective name is reset every time a `N` row is encountered, so only the last such row is recorded.
* Names for right-hand side and bounds are ignored, which means that
```
RHS
    rhs1      r1                2.0    r2                6.0
    rhs2      r1               -2.0    r2               -6.0
```
would yield right-hand sides of `-2` and `-6` for rows `r1` and `r2`, respectively.

Obviously, nobody follows the same convention, so I would propose to do as follows:
* The first `N` row is selected as the objective. Other `N` rows are ignored.
  Consequently, entries in subsequent sections that correspond to unregistered rows should be ignored, not raise an error. If this sounds bad or if you really want to raise an error, then one should keep track of these extra `N` rows.
* The first  name encountered in `RHS`, `BOUNDS`, `RANGES` is selected; others (if any) are ignored
* Duplicate coefficients in the `COLUMNS` and `QUADOBJ` sections are added together. This follows the default behavior of creating a sparse matrix from the coefficients list: duplicate entries are added.
* Duplicate entries in `RHS`, `BOUNDS`, `RANGES` sections over-write previous entries.

Here's a quick and non-exhaustive overview of what others do:
* [lpsolve](http://lpsolve.sourceforge.net/5.5/mps-format.htm):
  >The RHS section allows one or more right-hand-side vectors to be
defined; most people don't bother having more than one.

* [CPLEX docs](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.10.0/ilog.odms.cplex.help/CPLEX/UsrMan/topics/progr_consid/input_output/manageIO_file_formats_MPS.html):
  > The MPS format allows multiple righthand sides (RHSs), multiple bounds, and multiple range vectors. It also allows extra free rows. Together, these features are known as extra rim vectors. By default, the CPLEX MPS reader selects the first RHS, bound, and range definitions that it finds. The first free row (that is, N-type row) becomes the objective function, and the remaining free rows are discarded. The extra rim data are also discarded.

* The [Gurobi docs](https://www.gurobi.com/documentation/9.0/refman/mps_format.html) says
  > The name of the RHS is specified in the first field (column 5 in fixed format), but this name is ignored by the Gurobi reader
  and when I test with Gurobi 9.0, duplicate rhs entries for a given row are ignored (i.e., only the first occurrence of each row is recorded).
  > bound name (ignored)

* [Mosek docs](https://docs.mosek.com/9.1/dotnetapi/mps-format.html#doc-shared-mpsformat-sec-freeformat) do not mention how multiple entries are handled, however in practice it looks like the first occurrence of RHS is recorded, so in the example above, the line ` rhs2 ...` would be ignored.
If there are duplicate entries, only the last one is recorded, i.e., 
  ```
      rhs1      r1                2.0    r1                6.0
  ```
  would yield a right-hand side value of `6.0` for row `r1`.

**Comment by mtanneau** [comment]
> entries in subsequent sections that correspond to unregistered rows should be ignored, not raise an error

Currently, this case is not explicitly handled, however, a `KeyError` will be raised, e.g., [here](https://github.com/JuliaSmoothOptimizers/QPSReader.jl/blob/989ae248876c0a1b6f5ea24a4be99df20f5e763f/src/readqps.jl#L240), when a row is encountered whose name has not been seen before.

**Comment by dpo** [comment]
I don't have very strong feelings here but I'm in favor of an implementation that does not silently ignore data.

If we don't currently accept multiple objectives, I'm in favor of throwing an error when multiple objectives are defined, and possibly allowing an option (defaulting to `false`) that, when set to `true`, would cause subsequent objectives to be ignored.

Another possibility is to use logging to warn the user that objective rows (or right-hand sides) were ignored.

Summing duplicate coefficients seems reasonable. Again, a warning could be issued if we find any.

> Duplicate entries in RHS, BOUNDS, RANGES sections over-write previous entries.

Again I would prefer to raise an error and ask to user to explicitly set an option if they know what they're doing.

It would be good to have a list of MPS files that we currently can't handle and the reason why we can't handle them. We could tick off boxes as we make progress.

**Comment by mtanneau** [comment]
> Another possibility is to use logging to warn the user that objective rows (or right-hand sides) were ignored.

I would prefer that option over throwing an error if multiple objectives/RHS/bounds/etc. are encountered.

For instance, Mosek displays which objective/RHS/bounds/etc... was selected, with the convention that others are ignored:
```
Open file 'mps/stat96v1.mps.gz'
Reading started.
Using 'OBJ.FUNC' as objective vector
Read 972414 number of A nonzeros in 0.25 seconds.
Using 'RHS' as rhs vector
Using 'BOUNDS' as bound vector
Reading terminated. Time: 0.25
```
(from this [logfile](http://plato.asu.edu/ftp/lp_logs/msk_results/stat96v1.msb) in Hans Mittelmann's benchmark).
