### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by mtanneau** [JuliaSmoothOptimizers/QPSReader.jl#15]
I'll write a benchmark script before working on performance improvements.

I propose to use 3 benchmark sets:
* The Netlib LPs (available [here](http://www.numerical.rl.ac.uk/cute/netlib.html)): these are small LPs, in `.SIF` files and fixed MPS format.
* The Maros-Meszaros QPs ([here](http://www.doc.ic.ac.uk/~im/#DATA))
* The LPs of Hans Mittelmann's benchmark (see [here](http://plato.asu.edu/ftp/lpbar.html)). These are (much) larger LPs in `.mps`, some with integer variables, and some in free MPS format.

The reason for including a larger testset of instances would be to allow modifications that improve performance on large instances, while allowing a limited degradation on smaller instances.

For information, the readers in C/C++ solvers (commercial and open-source) are ~10-30x faster than the ones we have in Julia.

**Comment by dpo** [comment]
Sounds like a plan! It would be great to see some flame graphs in SVG to see what the bottlenecks are.

**Comment by mtanneau** [comment]
Closed by #30
